export const regAcomp = () => {
  return {
    cod: "",
    tipo_id: "",
    er_apel: "",
    do_apel: "",
    er_nom: "",
    do_nom: "",
    // _1er_apel: "",
    // _2do_apel: "",
    // _1er_nom: "",
    // _2do_nom: "",
    descrip: "",
    // nacim: "",
    // sexo: "",
    ciudad: "",
    descrip_ciudad: "",
    // descrip_depart: "",
    // zona: "",
    // descrip_zona: "",
    // tipo: "",
    // descrip_tipo: "",
    // eps: "",
    // descrip_eps: "",
    email: "",
    telefono: "",
    direccion: "",

    //anteriores variables
    // id_acomp: "",
    // tipo_id_acomp: "",
    // descrip_acomp: "",
    // er_apel_acomp: "",
    // do_apel_acomp: "",
    // er_nom_acomp: "",
    // do_nom_acomp: "",
    // telef_acomp: "",
    // email_acomp: "",
    // ciudad_acomp: "",
    // nom_ciu_acomp: "",
    // direcc_acomp: "",
  };
};
