export const regPaci = () => {
  return {
    cod: "",
    tipo_id: "",
    _1er_apel: "",
    _2do_apel: "",
    _1er_nom: "",
    _2do_nom: "",
    descrip: "",
    nacim: "",
    sexo: "",
    ciudad: "",
    descrip_ciudad: "",
    descrip_depart: "",
    zona: "",
    descrip_zona: "",
    tipo: "",
    descrip_tipo: "",
    eps: "",
    descrip_eps: "",
    tipo_afil: "",
    descrip_tipo_afil: "",
    telefono: "",
    direccion: "",
    cod_barrio: "",
    descrip_barrio: "",
    ocup: "",
    descrip_ocup: "",
    email: "",
    discap: "",
    paren_acomp: "",
  };
};
