export const reg_con851p_ = JSON.parse(
  JSON.stringify({
    codigo: null,
    estado: false,
    tipo: null,
    mensaje: null,
    func1: null,
    func2: null,
  })
);
export const msgCon851p_ = (codigo, mensaje) => {
  const mensajes = [
    { codigo: "00", mensaje: `¿Generar Impresión ${mensaje}?` },
    { codigo: "01", mensaje: "¿Desea grabar datos?" },
    { codigo: "02", mensaje: "¿Eliminar documento?" },
    { codigo: "03", mensaje: "¿Salir sin grabar?" },
    { codigo: "04", mensaje: "¿Continuar el proceso?" },
    { codigo: "05", mensaje: "¿Proceso total?" },
    { codigo: "06", mensaje: "¿Abrir excel?" },
    { codigo: "07", mensaje: "¿Documento ya existe, desea reprocesar?" },
    { codigo: "08", mensaje: "¿Codigo NO existe, desea crear?" },
    { codigo: "09", mensaje: `¿Desea actualizar ${mensaje}?` },
    { codigo: "10", mensaje: "¿Desea marcar el documento fact?" },
    { codigo: "11", mensaje: "¿Imprimir Stiker ?" },
    { codigo: "12", mensaje: "¿Mostrar Preparaciòn ?" },
    { codigo: "13", mensaje: "¿Abrir Nuevo Folio   ?" },
    { codigo: "14", mensaje: "¿Adicionar mas Registros?" },
    { codigo: "15", mensaje: "¿Factura ya existe, adicionar?" },
    { codigo: "16", mensaje: "¿Liquidar Flete?" },
    { codigo: "17", mensaje: "¿Enviar directo a la impres.?" },
    { codigo: "18", mensaje: "¿Desea convertir CRT EN SCL ?" },
    { codigo: "19", mensaje: "¿Pretende un cambio peligroso " },
    { codigo: "20", mensaje: "¿Diligenciar formulario NOPOS?" },
    { codigo: "21", mensaje: "¿Generar Imagen?" },
    { codigo: "22", mensaje: "¿Solicitar Autorizacion EPS  ?" },
    { codigo: "23", mensaje: "¿Bloquear impresion?" },
    { codigo: "24", mensaje: "¿Actualizar corresponsalia?" },
    { codigo: "25", mensaje: "¿Desea trasladar documento" },
    { codigo: "26", mensaje: "¿Desea actualizar votante?" },
    { codigo: "27", mensaje: "¿Desea imprimir recomendaciones" },
    { codigo: "28", mensaje: "¿Diligenciar procedimien. NOPOS" },
    { codigo: "29", mensaje: "¿Historia perinatal ?" },
    { codigo: "30", mensaje: "¿Aplica para exam. laboratorio?" },
    { codigo: "31", mensaje: "¿Aplica para exam. paraclinicos" },
    { codigo: "32", mensaje: "¿Ya fue radicada, es un reenvio?" },
    { codigo: "33", mensaje: "¿Imprimir recomendaciones dengue?" },
    { codigo: "34", mensaje: "¿Desea Cancelar solicitud?" },
    { codigo: "35", mensaje: "¿Desea Instalar JAVA?" },
    { codigo: "37", mensaje: "¿FINALIZAR PARTOGRAMA?" },
    { codigo: "38", mensaje: "¿REABRIR PARTOGRAMA?" },
    { codigo: "39", mensaje: "¿Desea crear nueva factura?" },
    { codigo: "40", mensaje: "¿Desea diligenciar Apache ?" },
    { codigo: "41", mensaje: "¿Llenar formular. Complementario?" },
    { codigo: "42", mensaje: "¿Desea formula trimestral?" },
    { codigo: "43", mensaje: "¿Desea mostrar Bases?" },
    { codigo: "44", mensaje: "¿Enviar Reporte via Email?" },
    { codigo: "45", mensaje: "¿Continuar sin cita Medica" },
    { codigo: "46", mensaje: "¿Enviar Mensaje de texto" },
    { codigo: "47", mensaje: "¿Ya Escaneo el documento" },
    { codigo: "48", mensaje: "¿Demanda inducida" },
    { codigo: "49", mensaje: "¿Cerrar historioas clinicas" },
    { codigo: "50", mensaje: "¿Desea Reliquidar Comprobantes" },
    { codigo: "51", mensaje: "¿Asignar Cama" },
    { codigo: "52", mensaje: "¿Cerrar control de transfusion?" },
    { codigo: "53", mensaje: "¿Imprimir Anexo tecnico?" },
    { codigo: "54", mensaje: `¿Desea eliminar ${mensaje}?` },
    { codigo: "55", mensaje: "¿Mostrar los eventos marcados como leídos?" },
    { codigo: "56", mensaje: "¿Desea formular semestral?" },
    { codigo: "58", mensaje: "¿Vacuna para covid-19" },
    { codigo: "59", mensaje: "¿Víctima de conflicto?" },
    { codigo: "consen", mensaje: "¿Seguro que quiere revocar consentimiento?" },
    { codigo: "macro", mensaje: "¿Seguro que quiere reemplazar por la macro?" },
    { codigo: "90", mensaje: "¿Licencia proxima a expirar" },
    { codigo: "IC", mensaje: "Guardar cofiguración de impresora?" },
    {
      codigo: "temp",
      mensaje:
        "La historia fue creada como TEMPORAL, seguro que desea salir sin finalizar ?",
    },
    { codigo: "CONFI-07", mensaje: "¿Desea crear contabilidad?" },
    { codigo: "CONFI-01", mensaje: "¿Desea eliminar contabilidad?" },
    { codigo: "SALIR", mensaje: "¿Desea cerrar sesión?" },
    { codigo: "MENU", mensaje: "¿Desea volver al menu principal?" },
    { codigo: "?", mensaje: `${mensaje}` },
  ];
  const find_mensaje = mensajes.find((e) => e.codigo == codigo)?.mensaje;
  return find_mensaje || "No se encontro CON851P";
};
