export const reg_con851_ = JSON.parse(
  JSON.stringify({
    codigo: null,
    estado: false,
    tipo: null,
    mensaje: null,
    func: null,
  })
);

export const msgCon851_ = (codigo, mensaje) => {
  const mensajes = [
    { codigo: "00", mensaje: `Ya existe la llave digitada ${mensaje}` },
    { codigo: "01", mensaje: `¡No existe el codigo ${mensaje}!` },
    { codigo: "02", mensaje: `¡El campo ${mensaje} requerido!` },
    { codigo: "03", mensaje: "¡Este dato es inválido!" },
    { codigo: "04", mensaje: " Falta % Ret. en plan cuentas   " },
    { codigo: "05", mensaje: `!El dato de ${mensaje} esta repetido!` },
    { codigo: "06", mensaje: " Documento es de otro NIT       " },
    { codigo: "07", mensaje: " No hay saldo disponible        " },
    { codigo: "08", mensaje: " No existe movimiento!          " },
    { codigo: "09", mensaje: " No hay saldo en el P.A.C.      " },
    { codigo: "10", mensaje: " No se pudo crear el archivo    " },
    { codigo: "11", mensaje: " Supera cupo asignado credito   " },
    { codigo: "12", mensaje: " Cliente lista negra (moroso)   " },
    { codigo: "13", mensaje: " Codigo desactivado             " },
    { codigo: "14", mensaje: " Transaccion restringida        " },
    { codigo: "15", mensaje: " Acceso restringido !!          " },
    { codigo: "16", mensaje: " Comprobante ya tiene recibo    " },
    { codigo: "17", mensaje: " Es el inicio del archivo !     " },
    { codigo: "18", mensaje: " No hay mas registros !         " },
    { codigo: "19", mensaje: " Empleado retirado!             " },
    { codigo: "20", mensaje: " Error! Concepto SALUD doble    " },
    { codigo: "21", mensaje: " Error! Concepto PENSION doble  " },
    { codigo: "22", mensaje: " Diferente cargo en una nomina  " },
    { codigo: "23", mensaje: " Dif. centro costos en nomina   " },
    { codigo: "24", mensaje: " Error en el cargo empleado     " },
    { codigo: "25", mensaje: " Error mas de 30 dias al mes    " },
    { codigo: "26", mensaje: " Clave de acceso invalida       " },
    { codigo: "27", mensaje: " NO existe codigo operador      " },
    { codigo: "28", mensaje: " NO se encontro ARCHUSU         " },
    { codigo: "29", mensaje: " NO se encontro REGCONT         " },
    { codigo: "30", mensaje: " Error! Documento NO aprobado   " },
    { codigo: "31", mensaje: " Atencion! cliente en MORA      " },
    { codigo: "32", mensaje: " Esta en un periodo no valido   " },
    { codigo: "33", mensaje: " Precio venta inferior a costo  " },
    { codigo: "34", mensaje: " Valor venta inferior a minimo  " },
    { codigo: "35", mensaje: " Error! Pedido YA despachado    " },
    { codigo: "36", mensaje: " No se permite descto fac mora  " },
    { codigo: "37", mensaje: " Fecha fuera de rango           " },
    { codigo: "38", mensaje: " Se actualizo aporte pension    " },
    { codigo: "39", mensaje: " Proceso termino satisfactoria  " },
    { codigo: "40", mensaje: " Error en el consecutivo        " },
    { codigo: "41", mensaje: " Peso inferior al minimo        " },
    { codigo: "42", mensaje: " Destare mayor al bruto         " },
    { codigo: "43", mensaje: " Destare menor al bruto         " },
    { codigo: "44", mensaje: " Debe repasar el renglon antes      " },
    { codigo: "45", mensaje: " No practico retencion en la fte    " },
    { codigo: "46", mensaje: " signo puede estar equivocado       " },
    { codigo: "47", mensaje: " No se puede cambiar comprob.       " },
    { codigo: "48", mensaje: " Sucursal no permitida              " },
    { codigo: "49", mensaje: " Opción no aplica en esta empresa   " },
    { codigo: "50", mensaje: " Plazo mayor a dias financiac.  " },
    { codigo: "51", mensaje: " Comprobante descuadrado !      " },
    { codigo: "52", mensaje: " Atencion, comprob. tiene mov.  " },
    { codigo: "53", mensaje: " Chequera es de otra cuenta     " },
    { codigo: "54", mensaje: " Chequera NO existe             " },
    { codigo: "55", mensaje: " Cheque NO habilitado           " },
    { codigo: "56", mensaje: " Cheque ya esta girado          " },
    { codigo: "57", mensaje: " Dato debe ser numerico !       " },
    { codigo: "58", mensaje: " Dato debe ser alfanumerico!    " },
    { codigo: "59", mensaje: " Precio de compra subio !       " },
    { codigo: "60", mensaje: " Para omitir reserva use 99999  " },
    { codigo: "61", mensaje: " Codigo no aplica con C.costo   " },
    { codigo: "62", mensaje: " Depreciar contra cta 5 OR 7    " },
    { codigo: "63", mensaje: " Comprobante NO tiene recibo    " },
    { codigo: "64", mensaje: " Serv. pub. no hay tarifas a�o  " },
    { codigo: "65", mensaje: " El tercero es exento de retenc." },
    { codigo: "66", mensaje: " La empresa no es ag. retenedor " },
    { codigo: "67", mensaje: " Si no es % digite 9            " },
    { codigo: "68", mensaje: " Falta llenar datos de usuario  " },
    { codigo: "69", mensaje: " Directorio Trabajo Errado      " },
    { codigo: "70", mensaje: " Documento cerrado              " },
    { codigo: "71", mensaje: " No aplica para fact. P o T     " },
    { codigo: "72", mensaje: " Factura bloqueada por RIPS     " },
    { codigo: "73", mensaje: " SEXO incompatible              " },
    { codigo: "74", mensaje: " Edad incompatible              " },
    { codigo: "75", mensaje: " Recuerde valoracion pediatra   " },
    { codigo: "76", mensaje: " No se puede valoracion pediatra" },
    { codigo: "77", mensaje: " No ha actualizado form. contrat" },
    {
      codigo: "78",
      mensaje: " Tipo de documento - No es valido con esta opcion.   ",
    },
    { codigo: "79", mensaje: " Medicamento NO POS             " },
    { codigo: "80", mensaje: " Usuario NO tiene derecho servic" },
    { codigo: "81", mensaje: " Fact.abre solo por oper cerro  " },
    { codigo: "82", mensaje: " Medico incompatible con clase  " },
    { codigo: "83", mensaje: " Opcion solo para embarazadas   " },
    { codigo: "84", mensaje: " La direccion es dato importante" },
    { codigo: "85", mensaje: " Arroz se liquida como grupo 2  " },
    { codigo: "86", mensaje: " Bloqueado solo menu contab.    " },
    { codigo: "87", mensaje: " Bloqueado solo inventarios     " },
    { codigo: "88", mensaje: " Periodo de Nomina bloqueado    " },
    { codigo: "89", mensaje: " Mes de trabajo NO bloqueado    " },
    { codigo: "90", mensaje: " Mes de trabajo bloqueado tot   " },
    { codigo: "91", mensaje: " Ubiquese en el mes adecuado    " },
    { codigo: "92", mensaje: " Opcion restringida en CONSOL.  " },
    { codigo: "93", mensaje: " Hay codigos en un subnivel     " },
    { codigo: "94", mensaje: " No corresponde Fuente Financ.  " },
    { codigo: "95", mensaje: " Se cambio el numero factura    " },
    { codigo: "96", mensaje: " Falta elaborar la glosa        " },
    { codigo: "97", mensaje: " Documento tiene endoso         " },
    { codigo: "98", mensaje: " Tiquete ya fue liquidado       " },
    { codigo: "99", mensaje: " No existe macro para ese artic " },
    { codigo: "9A", mensaje: "Falta comp. consulta           " },
    { codigo: "9B", mensaje: "El monto facturado supera 75%  " },
    { codigo: "9C", mensaje: "Esta a punto de copar contrato " },
    { codigo: "9D", mensaje: "Supera en monto del contrato   " },
    { codigo: "9E", mensaje: "Supera el promedio historico   " },
    { codigo: "9F", mensaje: "No se encontro cita medica     " },
    { codigo: "9G", mensaje: "Hace 90 dias no cambia clave   " },
    { codigo: "9H", mensaje: "la clave debe ser distinta     " },
    { codigo: "9I", mensaje: "Error en digito de verificac.  " },
    { codigo: "9J", mensaje: "Factura esta en otro RIPS      " },
    { codigo: "9K", mensaje: "ARROZ GRADO 2                  " },
    { codigo: "9L", mensaje: "ARROZ GRADO 3                  " },
    { codigo: "9M", mensaje: "DOCUMENTO YA ESTA CAUSADO      " },
    { codigo: "9N", mensaje: "Clave errada tercer aviso      " },
    { codigo: "9O", mensaje: "Supera Nro max de registros    " },
    { codigo: "9P", mensaje: "No se ha digitado el resultado " },
    { codigo: "9Q", mensaje: "Fuera de horario               " },
    { codigo: "9R", mensaje: "No existe cod cups             " },
    { codigo: "9S", mensaje: "Paciente es de otra EPS        " },
    { codigo: "9T", mensaje: "Tarifa no corresponde reserva  " },
    { codigo: "9U", mensaje: "Falta codigo entid administrad." },
    { codigo: "9V", mensaje: "No se puede modificar historia " },
    { codigo: "9W", mensaje: "Falta config. nomina dispersa  " },
    { codigo: "9X", mensaje: "Error en personal que atiende  " },
    { codigo: "9Y", mensaje: "Historia debe estar abierta    " },
    { codigo: "9Z", mensaje: "No alcanza el tiempo cita      " },
    { codigo: "1A", mensaje: "Debe recalcular saldos 963     " },
    { codigo: "1B", mensaje: "Falta cerrar la factura        " },
    { codigo: "1C", mensaje: "Falta cerrar historia clinica  " },
    { codigo: "1D", mensaje: "Presione cualquier tecla       " },
    { codigo: "1E", mensaje: "Directorio mas de 10 caracteres" },
    { codigo: "1F", mensaje: "Cama no disponible             " },
    { codigo: "1G", mensaje: "Cita ya tiene factura          " },
    { codigo: "1H", mensaje: "Ya se genero prefactura op949  " },
    { codigo: "1I", mensaje: "Recuerde datos recien nacido   " },
    { codigo: "1J", mensaje: "Art. no caben en la factura    " },
    { codigo: "1K", mensaje: "Paciente tiene factura P abiert" },
    { codigo: "1L", mensaje: "No se encontro informe APACHE  " },
    { codigo: "1M", mensaje: "Lote no corresponde con articul" },
    { codigo: "1N", mensaje: "Lote farmaceutico ya existe    " },
    { codigo: "1O", mensaje: "No se puede cerrar habitac P   " },
    { codigo: "1P", mensaje: "No uso el lector de barras     " },
    { codigo: "1Q", mensaje: "Falta asignar # fact a hiclinic" },
    { codigo: "1R", mensaje: "Reingreso mayor a 15 dias      " },
    { codigo: "1S", mensaje: "Exedio maximo nro de entradas  " },
    { codigo: "1T", mensaje: "No se encontro contrato        " },
    { codigo: "1U", mensaje: "Se actualizaron llamadas tel.  " },
    { codigo: "1V", mensaje: "formato desconocido            " },
    { codigo: "1W", mensaje: "factura es de resumen capitacion" },
    { codigo: "1X", mensaje: "No tiene asignado cupo credito " },
    { codigo: "1Y", mensaje: "Datos factura no coinciden      " },
    { codigo: "1Z", mensaje: "Documento no se ha vencido      " },
    { codigo: "2A", mensaje: "Consulta externa restringida    " },
    { codigo: "2B", mensaje: "Ya existe ese paciente          " },
    { codigo: "2C", mensaje: "Error en Grupo Sanguineo        " },
    { codigo: "2D", mensaje: "Datos del documento cambiaron   " },
    { codigo: "2E", mensaje: "Falta fecha de ingreso/retiro   " },
    { codigo: "2F", mensaje: "Vehiculo no es ambulancia       " },
    { codigo: "2G", mensaje: "Se ha modificado el PATH        " },
    { codigo: "2H", mensaje: "No ha liquidado Seguro (F10)    " },
    { codigo: "2I", mensaje: "No aplica para particulares     " },
    { codigo: "2J", mensaje: "Solo aplica para urgencias      " },
    { codigo: "2K", mensaje: "e-mail es un dato importante    " },
    { codigo: "2L", mensaje: "No se encontraron sucursales    " },
    { codigo: "2M", mensaje: "contrato del paci no corresp.   " },
    { codigo: "2N", mensaje: "Paciente no tiene CARNET        " },
    { codigo: "2O", mensaje: "Falta % interes del periodo     " },
    { codigo: "2P", mensaje: "Falta configurar el periodo     " },
    { codigo: "2Q", mensaje: "Ese dia el medico no atiende    " },
    { codigo: "2R", mensaje: "Factura es de otro ano          " },
    { codigo: "2S", mensaje: "Tercero registra EMBARGOS       " },
    { codigo: "2T", mensaje: "Paciente suspendido             " },
    { codigo: "2U", mensaje: "Bloqueo solo FACTURACION        " },
    { codigo: "2V", mensaje: "Comprobante no esta marcado     " },
    { codigo: "2W", mensaje: "Comprobante NO se pudo grabar   " },
    { codigo: "2X", mensaje: "Debe seleccionar folio nuevo    " },
    { codigo: "2Y", mensaje: "Doc. Bloqueado para Impresion   " },
    { codigo: "2Z", mensaje: "Recuerde llenar formul notifici." },
    { codigo: "3A", mensaje: "No existe historia clinica      " },
    { codigo: "3B", mensaje: "Hay Antecedentes alergicos      " },
    { codigo: "3C", mensaje: "MENSAJE SOI                     " },
    { codigo: "3D", mensaje: "ESPECIALIDAD NO CONCUERDA CUP   " },
    { codigo: "3E", mensaje: "PER. ATIENDE NO CONCUERDA CUP   " },
    { codigo: "3F", mensaje: "Factura no es para tipo paci.   " },
    { codigo: "3G", mensaje: "Fact A, solo cierran en mes Ing." },
    { codigo: "3H", mensaje: "No genera cargos                " },
    { codigo: "3I", mensaje: "Use opcion 72 para epicrisis    " },
    { codigo: "3J", mensaje: "CTA para cobrar multa inasistenc" },
    { codigo: "3K", mensaje: "Falta NIT entidad prestadora ser" },
    { codigo: "3L", mensaje: "Solo aplica para facturas capita" },
    { codigo: "3M", mensaje: "No pudo actualizar inventarios  " },
    { codigo: "3N", mensaje: "Hay diferencia en cantidades    " },
    { codigo: "3O", mensaje: "Paciente tiene fiebre           " },
    { codigo: "3P", mensaje: "Paciente con frec. resp rapida  " },
    { codigo: "3Q", mensaje: "Excede % Descuento              " },
    { codigo: "3R", mensaje: "Solo factura paciente adul> y ob" },
    { codigo: "3S", mensaje: "Solo factura paciente adul>     " },
    { codigo: "3T", mensaje: "No puede ser el mismo operador  " },
    { codigo: "3U", mensaje: "Tiene saldo pendiente por pagar " },
    { codigo: "3V", mensaje: "No configuro copia de seguridad " },
    { codigo: "3W", mensaje: "No hay contrato de mantenimiento" },
    { codigo: "3X", mensaje: "El votante ya fue visitado      " },
    { codigo: "3Y", mensaje: "La cita esta fuera de rango resp" },
    { codigo: "3Z", mensaje: "El votante ya fue agendado      " },
    { codigo: "4A", mensaje: "Excede el tiempo Max Permitido  " },
    { codigo: "4B", mensaje: "Solo aplica para p y p          " },
    { codigo: "4C", mensaje: "No ha capturado Foto            " },
    { codigo: "4D", mensaje: "Prepare el paciente para la foto" },
    { codigo: "4E", mensaje: "No aplica para especialistas    " },
    { codigo: "4F", mensaje: "Solo aplica para especialistas  " },
    { codigo: "4G", mensaje: "Vencim certificado Dpen Economic" },
    { codigo: "4H", mensaje: "Actualizar Colegio Paciente 9714" },
    { codigo: "4I", mensaje: "Error Factura con Retencion     " },
    { codigo: "4J", mensaje: "Actualizar Etinas Paciente 97765" },
    { codigo: "4K", mensaje: "Esta usando finalidad 10 en pyp " },
    { codigo: "4L", mensaje: "Numero de Radicado no existe    " },
    { codigo: "4M", mensaje: "Nro de Radicado ya tiene respues" },
    { codigo: "4N", mensaje: "Nro de Radic no se puede modific" },
    { codigo: "4O", mensaje: "CAMA DISPONIBLE POR LA OPC. 6-1 " },
    { codigo: "4P", mensaje: "No Existe Precio de Venta !     " },
    { codigo: "4Q", mensaje: "pct. esta acostado - use opc 9-3" },
    { codigo: "4R", mensaje: "Inconsistencia en edad gestacion" },
    { codigo: "4S", mensaje: "Inconsistencia Nro gestaciones  " },
    { codigo: "4T", mensaje: "CUPS ya fue facturado ese dia   " },
    { codigo: "4U", mensaje: "BLOQUEO FACTURACION Y NOMINA    " },
    { codigo: "4V", mensaje: "BLOQUEO FACTURACION E INVENT    " },
    { codigo: "4W", mensaje: "BLOQUEO FACTUR, INVENT, NOMINA  " },
    { codigo: "4X", mensaje: "Actualizar Comudidad Paci  971H " },
    { codigo: "4Y", mensaje: "Actualizar Resguardo Paci  971I " },
    { codigo: "4Z", mensaje: "Actualizar Resguardo Paci  971I " },
    { codigo: "5A", mensaje: "Solo administrador prosoft      " },
    { codigo: "5B", mensaje: "Paciente tutela                 " },
    { codigo: "5C", mensaje: "Solo aplica para maestra capitac" },
    { codigo: "5D", mensaje: "Historia no es de salud ocupacio" },
    { codigo: "5E", mensaje: "Documento ya fue Impreso !!     " },
    { codigo: "5F", mensaje: "Documento tiene  movimiento!    " },
    { codigo: "5G", mensaje: "Factura de Contado !            " },
    { codigo: "5H", mensaje: "cita no puede ser menor a 5 dias" },
    { codigo: "5I", mensaje: "factura tiene devolucion!       " },
    { codigo: "5J", mensaje: "Paciente alto Costo             " },
    { codigo: "5K", mensaje: "stop minimo medicamentos        " },
    { codigo: "5L", mensaje: "Atencion codigo no C.I.S        " },
    { codigo: "5M", mensaje: "Acceso Denegado Sesion activa   " },
    { codigo: "5N", mensaje: "Falta configurar Prefijo Factura" },
    { codigo: "5O", mensaje: "Proceso suspendido              " },
    { codigo: "5P", mensaje: "Solo se admite S, N o I         " },
    { codigo: "5Q", mensaje: "Paciente especial               " },
    { codigo: "5R", mensaje: "Debe actualizar C.D.P.          " },
    { codigo: "5S", mensaje: "La factura es de otro convenio  " },
    { codigo: "5T", mensaje: "Resolucion DIAN Vencida         " },
    { codigo: "5U", mensaje: "Resolucion DIAN por vencer !    " },
    { codigo: "5V", mensaje: "Paciente Multiconsultante       " },
    { codigo: "6A", mensaje: "Falta actualizar sobretasa      " },
    { codigo: "6B", mensaje: "Falta valor UVT del a�o         " },
    { codigo: "6C", mensaje: "Debe ser una cta provisiones    " },
    { codigo: "6D", mensaje: "Diferencia en tarifa de IVA     " },
    { codigo: "6E", mensaje: "Paciente esta embarazada        " },
    { codigo: "6F", mensaje: "Se requiere diligenciar CLAP    " },
    { codigo: "6G", mensaje: "CLAP esta CERRADO!              " },
    { codigo: "6H", mensaje: "Falta precio compra!            " },
    { codigo: "6I", mensaje: "Tercero asociado a otro NIT     " },
    { codigo: "6J", mensaje: "Tercero solo retiene si hay base" },
    { codigo: "6K", mensaje: "No aplica para persona juridica " },
    { codigo: "6L", mensaje: "No se encontro orden salida med." },
    { codigo: "6M", mensaje: "Codigo mal clasificado          " },
    { codigo: "6N", mensaje: "Comprob. ya tiene boleta salida " },
    { codigo: "6O", mensaje: "Documento ya fue aprobado       " },
    { codigo: "6P", mensaje: "Depend. de operador no autorizad" },
    { codigo: "6Q", mensaje: "Debe abrir una nueva historia   " },
    { codigo: "6R", mensaje: "Solo se procesan facturas cerrad" },
    { codigo: "6T", mensaje: "Error en la fecha de presentac. " },
    { codigo: "6U", mensaje: "Mensaje citas embarazadas       " },
    { codigo: "6V", mensaje: "NO SE EFECTUO NINGUN CAMBIO     " },
    { codigo: "6W", mensaje: "CUPS BLOQUEADO PARA ESE NIT     " },
    { codigo: "6X", mensaje: "No es necesario imprimir documen" },
    { codigo: "6Y", mensaje: "Intenta disminuir precio venta! " },
    { codigo: "7A", mensaje: "Paciente cronico                " },
    { codigo: "7B", mensaje: "Limite de citas cumplida        " },
    { codigo: "7C", mensaje: "Limite de Dias de Citas         " },
    { codigo: "7D", mensaje: "Fecha u Hora Menor al ingreso   " },
    { codigo: "7E", mensaje: "Causa Externa incompatible DX   " },
    { codigo: "7F", mensaje: "Impresion unica                 " },
    { codigo: "7G", mensaje: "Cita se encuentra cancelada     " },
    { codigo: "7H", mensaje: "Medicamento No permitido x clasi" },
    { codigo: "7I", mensaje: "Pacte ya registra 1ra vez consul" },
    { codigo: "7J", mensaje: "Pacte ya registra 1ra vez consul" },
    { codigo: "7K", mensaje: "Medicamento Homologo            " },
    { codigo: "7O", mensaje: "Paciente de factura             " },
    { codigo: "7P", mensaje: "Paciente tiene movimiento       " },
    { codigo: "7Q", mensaje: "Vencimiento Resolucion Dian     " },
    { codigo: "7R", mensaje: "Cups Bloquedo por jefe facturac " },
    { codigo: "7S", mensaje: "Cita mal facturada              " },
    { codigo: "7T", mensaje: "Rips Bloqueado                  " },
    { codigo: "7W", mensaje: "Reingreso a Triage < 24 h       " },
    { codigo: "7U", mensaje: "Clase de servicio Bloqueada FACT" },
    { codigo: "7V", mensaje: "Glosa duplicada Excel           " },
    { codigo: "7W", mensaje: "Posible reingreso Traige        " },
    { codigo: "7X", mensaje: "Cups Desactualizado nueva Resl  " },
    { codigo: "7Z", mensaje: "Factura No permite art con IVA  " },
    { codigo: "8A", mensaje: "Falta Conf.Actividad Economica  " },
    { codigo: "8B", mensaje: "Proceso copia iniciada..        " },
    { codigo: "8C", mensaje: "Estudio Ant.No comparativo      " },
    { codigo: "8D", mensaje: "Fecha de Fact Mayor a boleta sal" },
    { codigo: "8E", mensaje: "La finalidad no igual a la cita " },
    { codigo: "8F", mensaje: "El cod medicamento no igual pend" },
    { codigo: "8G", mensaje: "supera la cantidad de pendientes" },
    { codigo: "8H", mensaje: "Pendiente ya tiene despacho     " },
    { codigo: "8I", mensaje: "Paciente con posible abuxo      " },
    { codigo: "8J", mensaje: "Cups nivel no igual a Nivel Fact" },
    { codigo: "8K", mensaje: "Fact actualmente no tiene Radica" },
    { codigo: "8L", mensaje: "Minimo 10 Caracteres            " },
    { codigo: "8M", mensaje: "Factura no es igual a la HC     " },
    { codigo: "8N", mensaje: "Cups ya fue Autori mismo mes    " },
    { codigo: "8O", mensaje: "Valor de la Poliza super 75 %   " },
    { codigo: "8P", mensaje: "Valor de la Poliza super 80 %   " },
    { codigo: "8Q", mensaje: "Valor de la Poliza super 85 %   " },
    { codigo: "8R", mensaje: "Valor de la Poliza super 90 %   " },
    { codigo: "8S", mensaje: "Valor de la Poliza super 95 %   " },
    { codigo: "8T", mensaje: "Candidato adulto Mayor Quinqueni" },
    { codigo: "8Y", mensaje: "Valor errado en el total        " },
    { codigo: "8U", mensaje: "Nro de autorizacion en otra fact" },
    { codigo: "8V", mensaje: "Candidato adolescencia          " },
    { codigo: "8W", mensaje: "Candidato juventud              " },
    { codigo: "8X", mensaje: "CUPS ya fue facturado 6 meses   " },
    { codigo: "8Y", mensaje: "la suma del producto ERROR      " },
    { codigo: "8Z", mensaje: "la compra no puede superar 9999 " },
    { codigo: "R6", mensaje: "Ya esta registrado entregado    " },
    { codigo: "R7", mensaje: "Articulo no esta en tarifa medic" },
    { codigo: "R8", mensaje: "No definido comportamiento factu" },
    { codigo: "R9", mensaje: "Bloqueado por cufe factu electro" },
    { codigo: "R0", mensaje: "Forma de copago errado no acept " },
    { codigo: "S0", mensaje: "Lote esta vencido " },
    { codigo: "K2", mensaje: " Precio de compra bajo  !       " },
    { codigo: "0A", mensaje: "INSTALANDO JAVA                 " },
    { codigo: "0C", mensaje: "ERROR CON CREA-HIS.EXE          " },
    { codigo: "0D", mensaje: "YA EXISTE UN PARTO PARA ESTE FOLIO" },
    { codigo: "0E", mensaje: "EXISTE UN PARTO EN MENOS DE 6 MESES" },
    { codigo: "0F", mensaje: "INSTALANDO POWER COBOL          " },
    { codigo: "0G", mensaje: "EL EMPLEADO NO CUMPLE 48 HORAS  " },
    { codigo: "0H", mensaje: "EL EMPLEADO NO CUMPLE 192 HORAS " },
    { codigo: "A0", mensaje: "No tiene problema en desarrollo " },
    { codigo: "A1", mensaje: "Enfermedad muy grave            " },
    { codigo: "A2", mensaje: "Neumonia grave                  " },
    { codigo: "A3", mensaje: "Neumonia                        " },
    { codigo: "A4", mensaje: "Tos o resfriado                 " },
    { codigo: "A5", mensaje: "Sibilancia                      " },
    { codigo: "A6", mensaje: "DIARREA, deshidratacion grave   " },
    { codigo: "A7", mensaje: "DIARREA  deshidratacion leve    " },
    { codigo: "A8", mensaje: "DIARREA  RIESGO DESHIDRATACION  " },
    { codigo: "A9", mensaje: "Diarrea persistente grave       " },
    { codigo: "AA", mensaje: "Diarrea persistente             " },
    { codigo: "AB", mensaje: "Disenteria                      " },
    { codigo: "AC", mensaje: "Enfermedad febril muy grave     " },
    { codigo: "AD", mensaje: "Enfermedad febril intermedio    " },
    { codigo: "AE", mensaje: "Enfermedad febril               " },
    { codigo: "AF", mensaje: "Sospecha de malaria complicada  " },
    { codigo: "AG", mensaje: "Sospecha malaria no complicada  " },
    { codigo: "AH", mensaje: "Dengue grave                    " },
    { codigo: "AI", mensaje: "Dengue con signos de alarma     " },
    { codigo: "AJ", mensaje: "Sospecha de sarampion           " },
    { codigo: "AK", mensaje: "Mastoiditis                     " },
    { codigo: "AL", mensaje: "Otitis media aguda              " },
    { codigo: "AM", mensaje: "Otitis media CRONICA            " },
    { codigo: "AN", mensaje: "No tiene otitis media           " },
    { codigo: "AO", mensaje: "Faringoamigdalitis estreptococica" },
    { codigo: "AP", mensaje: "Faringoamigdalitis viral         " },
    { codigo: "AQ", mensaje: "No tiene faringoamigdalitis      " },
    { codigo: "AR", mensaje: "maltrato fisico y/o abuso sexual" },
    { codigo: "AS", mensaje: "Sospecha de maltrato             " },
    { codigo: "AT", mensaje: "Falla en la crianza              " },
    { codigo: "AU", mensaje: "No hay sospecha de maltrato      " },
    { codigo: "AV", mensaje: "Desnutricion severa              " },
    { codigo: "AW", mensaje: "Desnutricion                     " },
    { codigo: "AX", mensaje: "No tiene DESNUTRICION            " },
    { codigo: "AY", mensaje: "Riesgo de problema en desarrollo" },
    { codigo: "AZ", mensaje: "Desarrollo normal con fact riesg" },
    { codigo: "B0", mensaje: "Falta Estudio Principal         " },
    { codigo: "B1", mensaje: "No aplica para esa unid. servic." },
    { codigo: "B2", mensaje: "Doc. aplica solo para devolucion" },
    { codigo: "B3", mensaje: "ES OBLIGATORIO DILIGENCIAR AIEPI" },
    { codigo: "B4", mensaje: "Doc. no aplica para devoluciones" },
    { codigo: "B5", mensaje: "Dev.del mes superan tope Aux.Tra" },
    { codigo: "B6", mensaje: "Actu Dependencia laboral Opc.7C1" },
    { codigo: "B7", mensaje: "Operador no es igual a correspon" },
    { codigo: "B8", mensaje: "Vencio certificado de estudio   " },
    { codigo: "B9", mensaje: "Error Configuracion de Concepto " },
    { codigo: "BA", mensaje: "Obligatorio Actualizar Regimen  " },
    { codigo: "BB", mensaje: "Paciente con sobrepeso          " },
    { codigo: "BC", mensaje: "Paciente OBESO                  " },
    { codigo: "BD", mensaje: "Paciente delgadez moderada      " },
    { codigo: "BE", mensaje: "Paciente delgadez severa        " },
    { codigo: "BF", mensaje: "Perimetro cefalico -2 inferior  " },
    { codigo: "BG", mensaje: "Perimetro cefalico +2 mayor     " },
    { codigo: "BH", mensaje: "Probable retraso desarrollo     " },
    { codigo: "BI", mensaje: "PESO MUY BAJO                   " },
    { codigo: "BJ", mensaje: "PESO BAJO O EN RIESGO           " },
    { codigo: "BK", mensaje: "FRECUENCIA CARDIACA ANORMAL     " },
    { codigo: "BL", mensaje: "FRECUENCIA RESPIRATORIA ANORMAL " },
    { codigo: "BM", mensaje: "TEMPERATURA ANORMAL             " },
    { codigo: "BN", mensaje: "CRUP GRAVE                      " },
    { codigo: "BO", mensaje: "BRONQUIOLITIS GRAVE             " },
    { codigo: "BP", mensaje: "SIBILANCIA GRAVE                " },
    { codigo: "BQ", mensaje: "CRUP LEVE                       " },
    { codigo: "BR", mensaje: "BRONQUIOLITIS LEVE              " },
    { codigo: "BS", mensaje: "DIARREA SIN DESHIDRATACION      " },
    { codigo: "BT", mensaje: "DIARREA PERSISTENTE GRAVE       " },
    { codigo: "BU", mensaje: "DIARREA PERSISTENTE LEVE        " },
    { codigo: "BV", mensaje: "Otitis media RECURRENTE         " },
    { codigo: "BW", mensaje: "RIESGO DESNUTRICION             " },
    { codigo: "BX", mensaje: "ANEMIA SEVERA                   " },
    { codigo: "BY", mensaje: "ANEMIA LEVE                     " },
    { codigo: "BZ", mensaje: "NO TIENE ANEMIA                 " },
    { codigo: "C1", mensaje: "SIDA ESTADIO 1                  " },
    { codigo: "C2", mensaje: "SIDA ESTADIO 2                  " },
    { codigo: "C3", mensaje: "SIDA ESTADIO 3                  " },
    { codigo: "C4", mensaje: "SIDA ESTADIO 4                  " },
    { codigo: "C5", mensaje: "POSIBLE CANCER                  " },
    { codigo: "C6", mensaje: "ALGUN RIESGO DE CANCER          " },
    { codigo: "C7", mensaje: "POCA PROBABILIDAD DE CANCER     " },
    { codigo: "CA", mensaje: "PROBABLE DE DENGUE              " },
    { codigo: "CB", mensaje: "MALTRATO FISICO GRAVE           " },
    { codigo: "CC", mensaje: "MALTRATO FISICO                 " },
    { codigo: "CD", mensaje: "ABUSO SEXUAL                    " },
    { codigo: "CE", mensaje: "SOSPECHA DE ABUSO SEXUAL        " },
    { codigo: "CF", mensaje: "NEGLIGENCIA O ABANDONO          " },
    { codigo: "CG", mensaje: "NO HAY SOSPECHA MALTRATO        " },
    { codigo: "CH", mensaje: "PROBABLE RETRASO DEL DESARROLLO " },
    { codigo: "CI", mensaje: "RIESGO DE PROBLEMA EN DESARROLLO" },
    { codigo: "CJ", mensaje: "DESARROLLO NORMAL CON RIESGO    " },
    { codigo: "CK", mensaje: "DESARROLLO NORMAL               " },
    { codigo: "CL", mensaje: "ESTADO EPILEPTICO               " },
    { codigo: "CM", mensaje: "PROBLEMA NEUROLOGICO GRAVE      " },
    { codigo: "CN", mensaje: "EPILEPSIA CON CRISIS GENERALIZAD" },
    { codigo: "CO", mensaje: "EPILEPSIA CON CRISIS FOCAL      " },
    { codigo: "CP", mensaje: "EPILEPSIA CON CRISIS DE AUSENCIA" },
    { codigo: "CQ", mensaje: "NO TIENE EPILEPSIA              " },
    { codigo: "CR", mensaje: "SOSPECHA TUBERCULOSIS GRAVE     " },
    { codigo: "CS", mensaje: "TUBERCULOSIS CONFIRMADA         " },
    { codigo: "CT", mensaje: "TUBERCULOSIS CLINICA            " },
    { codigo: "CU", mensaje: "TUBERCULOSIS LATENTE            " },
    { codigo: "CV", mensaje: "CONTACTO CON TUBERCULOSIS       " },
    { codigo: "CW", mensaje: "INFECCION VIH SINTOMATICA CONFIR" },
    { codigo: "CX", mensaje: "INFECCION VIH CONFIRMADA        " },
    { codigo: "CY", mensaje: "SOSPECHA INFECCION VIH SINTOMATI" },
    { codigo: "CZ", mensaje: "EXPUESTO VIH                    " },
    { codigo: "D0", mensaje: "SURCOS EN MAS DE LA MITAD ANTERI" },
    { codigo: "D1", mensaje: "TEXTURA PIEL -FINA GELATINOSA   " },
    { codigo: "D2", mensaje: "TEXTURA PIEL -FINA LISA         " },
    { codigo: "D3", mensaje: "TEXTURA PIEL -MAS GRUESA ESCAMAS" },
    { codigo: "D4", mensaje: "TEXTURA PIEL -MAS GRUESA GRIETAS" },
    { codigo: "D5", mensaje: "TEXTURA PIEL -GRIETAS PROFUNDAS " },
    { codigo: "D6", mensaje: "TEXTURA PIEL -SIN PLIEGUES      " },
    { codigo: "E0", mensaje: "VIH SINTOMATICA IMPROBABLE      " },
    { codigo: "E1", mensaje: "VIH DESCARTADO                  " },
    { codigo: "E2", mensaje: "CETOSIS O CETOACIDOSIS DIABETICA" },
    { codigo: "E3", mensaje: "DIABETES MELLITUS               " },
    { codigo: "E4", mensaje: "POSIBLE DIABLETES MELLITUS      " },
    { codigo: "E5", mensaje: "INTOLERANCIA A LA GLUCOSA       " },
    { codigo: "E6", mensaje: "NO TIENE DIABETES MELLITUS      " },
    { codigo: "E7", mensaje: "CELULITIS FACIAL                " },
    { codigo: "E8", mensaje: "ENFERMEDAD BUCAL GRAVE          " },
    { codigo: "E9", mensaje: "TRAUMA BUCO DENTAL              " },
    { codigo: "EA", mensaje: "ESTOMATITIS                     " },
    { codigo: "EB", mensaje: "ENFERMEDAD DENTAL Y GINGIVAL    " },
    { codigo: "EC", mensaje: "ALTO RIESGO DE ENFERMEDAD BUCAL " },
    { codigo: "ED", mensaje: "BAJO RIESGO DE ENFERMEDAD BUCAL " },
    { codigo: "EE", mensaje: "PERIMETRO ABDOMINAL ALTO RIESGO " },
    { codigo: "EF", mensaje: "APENDIC.DEBE REALIZARSE EN 6 HOR" },
    { codigo: "EG", mensaje: "NO HAY ULTRASONOGRAFIA          " },
    { codigo: "EH", mensaje: "EMBARAZO DE ALTO RIESGO         " },
    { codigo: "EI", mensaje: "CANTIDAD DE MEDICANETO EN CERO  " },
    { codigo: "EJ", mensaje: "FALTAN DATOS DE CLASIFICACION   " },
    { codigo: "EK", mensaje: "FALTAN DATOS DE MADRE           " },
    { codigo: "EL", mensaje: "PACIENTE MUERTO SOLO ADMI O GEBC" },
    { codigo: "EM", mensaje: "INFECCION LOCAL                 " },
    { codigo: "EN", mensaje: "DIARREA CON SANGRE              " },
    { codigo: "EO", mensaje: "PROBLEMA SEVERO ALIMENTACION    " },
    { codigo: "EP", mensaje: "PROBLEMA LEVE ALIMENTACION      " },
    { codigo: "EQ", mensaje: "ERROR EN SOLICITUD DE PATOLOGIA " },
    { codigo: "G0", mensaje: "DIAGN. P Y P COMIENZAN POR Z    " },
    { codigo: "G1", mensaje: "DIAGN.MORBIL. NO PUEDE EMPEZAR Z" },
    { codigo: "G2", mensaje: "LA INCAPACIDAD NO SE PUEDE COMBI" },
    { codigo: "G3", mensaje: "ENFERMEDAD HUERFANA             " },
    { codigo: "G4", mensaje: "AISLAR POR BACTERIA RESISTENTE  " },
    { codigo: "H1", mensaje: "PESO NORMAL                     " },
    { codigo: "H2", mensaje: "DELGADEZ                        " },
    { codigo: "H3", mensaje: "TALLA MENOR RESPECTO A LA ULTIMA" },
    { codigo: "H4", mensaje: "DILIGENCIAR CONSENTIMIENTO INFOR" },
    { codigo: "RA", mensaje: "COD NO ESTA EN MAESTRO ARTICULOS" },
    { codigo: "U7", mensaje: "TANNER MASCULINO                " },
    { codigo: "U8", mensaje: "TANNER FEMENINO                 " },
    { codigo: "U9", mensaje: "TAMAÑO SENOS                    " },
    { codigo: "UA", mensaje: "TAMAÑO TESTICULOS               " },
    { codigo: "UM", mensaje: "Sesion no valida!" },
    { codigo: "thi", mensaje: "de error no identificado " },
    { codigo: "DESHAB", mensaje: "Opcion Deshabilitada Temporalmente" },
    { codigo: "BLOQUEADO", mensaje: "PROGRAMA BLOQUEADO" },
    { codigo: "USER", mensaje: `Datos ingresados invalidos` },
    { codigo: "CON", mensaje: "Correcto, iniciando sesión" },
    { codigo: "N1", mensaje: `${mensaje}` },
    { codigo: "I1", mensaje: `Impresión  generada ${mensaje}` },
    { codigo: "SERV", mensaje: "Error de conexión con el servidor" },
    { codigo: "ELIM", mensaje: "Datos eliminados correctamente" },
    { codigo: "FAV", mensaje: "No se puede agregar mas de 12 favoritos" },
    { codigo: "000", mensaje: "Error consultando datos" },
    { codigo: "NFAV", mensaje: "No tienes favoritos agregados" },
    { codigo: "NOSE", mensaje: "Error desconocido, arreglelo ya!" },
    {
      codigo: "NG",
      mensaje: `No fue posible guardar cambios. Res: ${mensaje}. Contacte con PROSOFT.`,
    },
    { codigo: "?", mensaje: `${mensaje}` },
  ];
  const find_mensaje = mensajes.find((e) => e.codigo == codigo)?.mensaje;
  return find_mensaje || "No se encontro CON851";
};
