export const reg_munic_ = () => {
  return {
    id_munic: null,
    cod_munic: null,
    cod_ciu: null,
    dpto_ciu_munic: null,
    ciu_ciu_munic: null,
    id_ciu: null,
    nombre_munic: null,
    direcc_munic: null,
    tel_munic: null,
    nit_munic: null,
    dv_munic: null,
    ult_fact_munic: null,
    barras_munic: null,
    encab_munic: null,
    funcionario_munic: null,
    cargo_munic: null,
    aprox_munic: null,
    copias_pys_munic: null,
    causac_munic: null,
    convenio_munic: null,
    impedir_pres_munic: null,
    int_cor_munic: null,
    mens_munic: null,
  };
};

export const form_munic_ = () => {
  return {
    cod_ciu: {
      id: "cod_ciu",
      label: "Cod. Ciud",
      placeholder: "Escribe codigo de ciuda",
      tipo: "number",
      maxlength: "5",
      disable: true,
      required: true,
      f0: ["f8"],
    },
    nombre_munic: {
      id: "nombre_munic",
      label: "Municipio",
      placeholder: "Escribe nombre de municipio",
      maxlength: "40",
      disable: true,
      required: true,
    },
    direcc_munic: {
      id: "direcc_munic",
      label: "Dirección",
      maxlength: "30",
      disable: true,
      required: true,
    },
    tel_munic: {
      id: "tel_munic",
      label: "Telefono",
      mask: "(###) ### - ####",
      maxlength: "16",
      disable: true,
      required: false,
    },
    nit_munic: {
      id: "nit_munic",
      label: "Nit",
      tipo: "number",
      maxlength: "10",
      disable: true,
      required: true,
    },
    dv_munic: {
      id: "dv_munic",
      label: "Digito de verificación",
      tipo: "number",
      maxlength: "1",
      disable: true,
      required: true,
    },
    ult_fact_munic: {
      id: "ult_fact_munic",
      label: "Ultima factura",
      mask: "###,###,###",
      maxlength: "9",
      disable: true,
      required: true,
    },
    barras_munic: {
      id: "barras_munic",
      label: "¿Usa lector codigo barras?",
      f0: ["f3"],
      disable: true,
      required: true,
    },
    encab_munic: {
      id: "encab_munic",
      label: "Encabezado",
      maxlength: "40",
      disable: true,
      required: true,
    },
    funcionario_munic: {
      id: "funcionario_munic",
      label: "Funcionario",
      maxlength: "40",
      disable: true,
      required: true,
    },
    cargo_munic: {
      id: "cargo_munic",
      label: "Cargo",
      maxlength: "40",
      disable: true,
      required: true,
    },
    aprox_munic: {
      id: "aprox_munic",
      label: "Forma de aproximar",
      disable: true,
      required: true,
    },
    copias_pys_munic: {
      id: "copias_pys_munic",
      label: "Numero de copias paz y salvo:",
      tipo: "number",
      maxlength: "1",
      disable: true,
      counter: true,
      required: true,
    },
    causac_munic: {
      id: "causac_munic",
      label: "Causac",
      maxlength: "1",
      disable: true,
      required: true,
    },
    convenio_munic: {
      id: "convenio_munic",
      label: "Convenio codigo de barras",
      maxlength: "13",
      disable: true,
    },
    impedir_pres_munic: {
      id: "impedir_pres_munic",
      label: "¿Impedir prescribir sobre ambiental?",
      disable: true,
      required: true,
      f0: ["f3"],
    },
    int_cor_munic: {
      id: "int_cor_munic",
      label: "Interes corriente mensual %",
      tipo: "number",
      maxlength: "5",
      disable: true,
      mask: "##.##",
      required: true,
    },
    mens_munic: {
      id: "mens_munic",
      label: "Fundamento legal para factura impuesto predial",
      maxlength: "475",
      disable: true,
      required: true,
      rows: 3,
      f0: ["f3"],
    },
  };
};
